### ISSUE TITLE
Update eXtraWidgets for NetLogo 6.x

### ISSUE THREAD

**Issue by nicolaspayette** [CRESS-Surrey/eXtraWidgets#155]
This means:
- [x] having a `5.x` and a `6.x` branch instead of one `master` branch;
- [x] building against the NetLogo 6.x jar(s?);
- [x] using the same Scala version as NetLogo 6.x (currently 2.10.4, but hopefully 2.11.x).

**Comment by wbarfuss** [comment]
Thanks for the cool extension.
Is there a version of xw for netlogo 6 currently available?
The readme says so, but I couldn't find any.

**Comment by nicolaspayette** [comment]
Thanks for pointing this out! It's there now:
https://github.com/CRESS-Surrey/eXtraWidgets/releases/tag/v2.0.0-BETA1

It's been tested with NetLogo 6.0-BETA1, but might not work with BETA2 (though you're welcome to try and let me know). I'll probably need to make some updates, but won't be able to do it right away.

**Comment by wbarfuss** [comment]
Thanks. I just tried it with netlogo 6.0 BETA2. Unfortunately it says
"This extension doesn't work with this version of NetLogo"
Looking forward to the updates !

**Comment by nicolaspayette** [comment]
Status update: we now have [a beta release](https://github.com/CRESS-Surrey/eXtraWidgets/releases/tag/v2.0.0-BETA3) that mostly works with NetLogo 6.0.2. The only thing that's currently holding a "proper" release is #165.

**Comment by nicolaspayette** [comment]
Other open issues notwithstanding, the extension works with NetLogo 6.4.0 as of #167.
