### ISSUE TITLE
Exporting and Importing Multi-choosers

### ISSUE THREAD

**Issue by stevebhall** [CRESS-Surrey/eXtraWidgets#162]
I'm using NetLogo 5.3.1

I see in the documentation that multi-chooser strings should export and import correctly but I can't seem to get them to do that for me.  

I can see that the selected-item is correctly written out in the JSON (e.g., 

  "roe_maxAnticipatory-1": {
    "COLOR": 58,
    "ENABLED?": true,
    "FONT-COLOR": 0,
    "FONT-SIZE": 12,
    "HEIGHT": 50,
    "HIDDEN?": false,
    "ITEMS": [
      "None",
      "Psych-1",
      "Psych-2",
      "Psych-3",
      "Pain-1",
      "Pain-2",
      "Pain-3",
      "Lethal"
    ],
    "KEY": "roe_maxAnticipatory-1",
    "KIND": "CHOOSER",
    "LABEL": "Max Anticipatory",
    "OPAQUE?": true,
    "SELECTED-ITEM": "Lethal",
    "TAB": "ROE",
    "WIDTH": 125,
    "X": 1105,
    "Y": 290
  },

But when its imported the selected-value remains the first option.  

Is this a bug or am I doing something wrong?

**Comment by nicolaspayette** [comment]
> Is this a bug or am I doing something wrong?

Thanks for reporting. It certainly looks like a bug.

I tried to poke around and find a possible cause, but I haven't touched that code base in a while and need to get myself reacquainted with it.

I'll probably start by tackling the long overdue #155, though. Would you consider moving to NetLogo 6.x if I get `xw` working in it?

**Comment by stevebhall** [comment]
Hi Nicholas,

To begin with allow me to say that I think XW is a seriously useful enhancement to NetLogo.  It makes it so much easier to build complex GUIs.

In regard to your question it looks like my code might well run under 6.x … and if not I’m convinced I could make it do so (and I’d like the excuse to do so).

The primary obstacle that originally held me back was my desire to use XW.

So ‘yes', let’s try going for the 6.x version.

Steve


On Nov 1, 2017, at 1:32 PM, Nicolas Payette <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a bug or am I doing something wrong?

Thanks for reporting. It certainly looks like a bug.

I tried to poke around and find a possible cause, but I haven't touched that code base in a while and need to get myself reacquainted with it.

I'll probably start by tackling the long overdue #155<https://github.com/CRESS-Surrey/eXtraWidgets/issues/155>, though. Would you consider moving to NetLogo 6.x if I get xw working in it?

**Comment by nicolaspayette** [comment]
@stevebhall, thanks for the good words about `xw`'s usefulness. :-)

I have upgraded the extension to work with NetLogo 6.0.2 and, hopefully, to fix the initialization of (multi-)chooser values on import.

I'd be grateful if you could give it a spin and tell me if it works for you:
https://github.com/CRESS-Surrey/eXtraWidgets/releases/tag/v2.0.0-BETA2

**Comment by stevebhall** [comment]
Nicholas,

Will do!

Thanks for being so quick on this!

Steven

Sent from my iPad

On Nov 11, 2017, at 11:56 AM, Nicolas Payette <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevebhall<https://github.com/stevebhall>, thanks for the good words about xw's usefulness. :-)

I have upgraded the extension to work with NetLogo 6.0.2 and, hopefully, to fix the initialization of (multi-)chooser values on import.

I'd be grateful if you could give it a spin and tell me if it works for you:
https://github.com/CRESS-Surrey/eXtraWidgets/releases/tag/v2.0.0-BETA2

**Comment by stevebhall** [comment]
Hi Nicholas,

After a bit a struggling to upgrade my model to run in NetLogo 6 I’ve now got it working again.

And the good/great news is that the xw save and load function is working great.  Hurray!

But I have noticed a superficial issue … that I can’t seem to solve in my code.

The xw ‘buttons', which use to have, by default, this beautiful gray shading on them, now appear solid white.  And I can’t seem to set them to any other color even when I explicitly ‘set’ the color.  (my other xw widgets seem to be colored fine).

Steve



On Nov 11, 2017, at 11:56 AM, Nicolas Payette <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevebhall<https://github.com/stevebhall>, thanks for the good words about xw's usefulness. :-)

I have upgraded the extension to work with NetLogo 6.0.2 and, hopefully, to fix the initialization of (multi-)chooser values on import.

I'd be grateful if you could give it a spin and tell me if it works for you:
https://github.com/CRESS-Surrey/eXtraWidgets/releases/tag/v2.0.0-BETA2

**Comment by nicolaspayette** [comment]
> xw save and load function is working great. Hurray!

Hurray indeed! And thanks for reporting and testing.

>The xw ‘buttons', which use to have, by default, this beautiful gray shading on them, now appear solid white. 

Thanks for reporting this too! I think this might be a new incarnation of #144, and I have moved the discussion there.
